### PR TITLE
V6.3 dev conc

### PR DESCRIPTION
**Pull request by tombisho**
This is to introduce a new disclosure control around how much contribution a single value can make to a summary statistic such as mean. At the moment I have shown how it could work for the mean.

### CODE REVIEW

**Comment by StuartWheater** [comment]
Do you want to merge this into 'master'? Should I create a 'v6.3-dev' branch?

**Comment by tombisho** [comment]
Good question! I guess really I just wanted a bit of a code review and
discussion about whether this is worth pursuing. So maybe a PR is not the
best vehicle for that...

**Comment by StuartWheater** [comment]
The target of this Pull Request appears to be "datashield:master" not "datashield:v6.3-dev"

**Comment by tombisho** [comment]
Sorry this is out of date - from last year I will close it and raise a new one when ready

**Pull request closed without merging**
