### PR TITLE
Fixed dstapply. Not all the parent.frames() are needed

### PR DESCRIPTION
**Pull request by tombisho**
Hi,

I have used my recent learning to update tapplyDS to work correctly with environments. I hope this helps!

Tom

### CODE REVIEW

**Comment by OllyButters** [comment]
@tombisho - did you mean to edit all those man pages?

**Comment by tombisho** [comment]
@OllyButters no I didn't mean to change them, they were just automatically generated like that when I built the package. If it is important I can go back and try and work out how to stop this happening? Or can you somehow block that as part of the merge?

**Comment by StuartWheater** [comment]
I can confirm new tapplyDS.R passes smoke tests when configured with both driver the "DSLiteDriver" and "OpalDriver".

**Comment by OllyButters** [comment]
Actually, I didn't give you enough credit @tombisho - your updated man pages bring them inline with the other existing man pages. Good tidy up skills!

**Comment by tombisho** [comment]
> 
> 
> Actually, I didn't give you enough credit @tombisho - your updated man pages bring them inline with the other existing man pages. Good tidy up skills!

That was definitely what I was trying to do and it didn't just happen by mistake

**Pull request merged**
